paisesList = [
    "Espanha",
    "Alemanha",
    "Andorra",
    "França",
    "Itália",
    "Áustria",
    "Portugal",
    "Reino Unido",
    "Irlanda",
    "Noruega",
    "Suécia",
    "Dinamarca",
    "Eslovênia",
    "Liechtenstein",
    "Bélgica",
    "Países Baixos",
    "Luxemburgo",
    "Mônaco",
    "Malta",
    "Croácia",
    "Sérvia",
    "Montenegro",
    "Islândia",
    "Finlândia",
]
